### ISSUE TITLE
Can't run spateo on google colab

### ISSUE THREAD

**Issue by vladimirkovacevic** [aristoteleo/spateo-release#170]
After downloading mousebrain_bin60.h5ad, installing spateo:
```
pip install spateo-release
```

and running:
```
fname_bin60 = "mousebrain_bin60.h5ad"
adata_bin60 = st.sample_data.mousebrain(fname_bin60)
```
I'm getting:
```
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/anndata/_io/utils.py](https://localhost:8080/#) in func_wrapper(elem, *args, **kwargs)
    155         try:
--> 156             return func(elem, *args, **kwargs)
    157         except Exception as e:

7 frames
KeyError: 'dict'

During handling of the above exception, another exception occurred:

AnnDataReadError                          Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/anndata/_io/utils.py](https://localhost:8080/#) in func_wrapper(elem, *args, **kwargs)
    160             else:
    161                 parent = _get_parent(elem)
--> 162                 raise AnnDataReadError(
    163                     f"Above error raised while reading key {elem.name!r} of "
    164                     f"type {type(elem)} from {parent}."

AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

Any idea why?
```
cat /etc/os-release
Ubuntu
VERSION="18.04.6 LTS (Bionic Beaver)"
```

**Comment by Xiaojieqiu** [comment]
Hi @vladimirkovacevic thanks for using spateo. I have released a new patch spateo v1.0.2,  could you please consider updating spateo and let us know? 
`pip install -U spateo-release`. 

Also what anndata version are you using? make sure to have anndata >= 0.8.0

**Comment by vladimirkovacevic** [comment]
@Xiaojieqiu, thank you for the fast response. It solved the issue. 
```
pip install -U spateo-release
```
installs anndata 0.7.5, so I had to update it to 0.8.0 after installing spateo. 
Also, SCC tutorial that I'm trying to run is using both spateo and dynamo and dynamo requires anndata==0.7.5, so I assume, it might create some collisions.

**Comment by Xiaojieqiu** [comment]
dynamo 1.2.0 is released and it requires anndata > 0.8.0. 

We will update the requirements for dynamo in spateo too

**Comment by Welcomelily** [comment]
@Xiaojieqiu Hi, I have update spateo-release to V1.0.2, also updata anndata to 0.8.0. but this problem remains. Any ideas for this?

**Comment by xuansuyang** [comment]
I have the same problem.Do you solve it now?

**Comment by Sichao25** [comment]
I can solve this by updating the anndata to 0.8.0 in colab. The tricky part is you have to make sure you are using the correct version of anndata. The easiest way might be to install anndata 0.8.0 first before installing spateo. You can run `import anndata` and `print(anndata.__version__)` before you run the analysis to check the current version.
